---
- block:
    - name: 'openbsd : check for system patches'
      command: 'syspatch -c'
      register: result
      become: true
      changed_when: result.stdout != ""  # noqa 602
      notify: install system patches
  rescue:
    - name: 'openbsd : log that syspatch -c failed'
      set_fact:
        task_failures: '{{ task_failures | default([]) | union(["syspatch -c"]) }}'
      changed_when: true
      notify: list failed tasks

- name: 'openbsd: add {{ dns_search_domain }} to dns search domains'
  lineinfile:
    path: '/etc/dhclient.conf'
    regexp: '^prepend domain-name '
    line: 'prepend domain-name "{{ dns_search_domain }} ";'
    create: true
    mode: '0644'
    owner: 'root'
    group: 'wheel'
  become: true
  notify: renew dhcp
  when: dns_search_domain is defined
