## Playbook to set up my Unix environment on Desktop Computers
# First time set up:
# 1. Install OS
# 2. Log in
# 3. Run: mkdir -p -m 700 ~/.ssh
# 3. Copy your SSH public key to ~/.ssh/authorized_keys
# 4. Install/Start SSH Server
#    - On Debian/Ubuntu, run: sudo apt install -y openssh-server
#    - On RedHat/CentOS/Fedora, run: sudo systemctl enable sshd.server ; sudo systemctl start sshd.server
#
# The first time this is run, the system probably has newly created SSH Host Keys.
# If you're using the 'sshserver' role's capability to install SSH Host Keys,
# on the Ansible system, run:
#  ANSIBLE_SSH_ARGS="-o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
#     ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop
#
# Once the SSH Host Keys have been installed or if you are going to install the new keys
# on the Ansible system, run:
#  ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop
#
# To keep configuration files up to date, run:
#  ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop -t configs
# or
#  ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop -t serverconfigs
# or
#  ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop -t userconfigs
#
# To install system/package updates, run:
#  ansible-playbook laptop-setup.yml --ask-vault-pass -e target=my_laptop -t updates

---
- hosts: "{{ target | default('localhost') }}"
  gather_facts: true

  roles:
    - role: handlers
    - role: become
    - role: sshserver
    - role: sshclient
    - role: unix_system
    - role: unix_desktop
    - role: gnome_desktop
