# This is a helper playbook which is included in setup_become_vault.yml
---
- block:
    - name: 'prompt user for {{ item }} become password'
      pause:
        prompt: 'Enter password for "{{ item }}" password_type: '
        echo: false
      no_log: true
      register: result

    - name: 'prompt user to confirm {{ item }} become password'
      pause:
        prompt: 'Confirm password for "{{ item }}" password_type: '
        echo: false
      no_log: true
      register: confirm

    - name: test that the password and confirmed password match
      assert:
        that: result.user_input == confirm.user_input
      no_log: true

    - name: 'Save the {{ item }} password in the passwords dict'
      set_fact:
        become_passwords: '{{ become_passwords | default({}) | combine({ item: result.user_input }) }}'
      no_log: true
  rescue:
    - name: passwords do not match, prompting again
      debug:
        msg: 'Error: Passwords for "{{ item }}" do not match. Try again.'

    - include_tasks: '_password_prompt.yml'
