---
- name: '_custom_deb_files : install custom deb files'
  apt:
    deb: '{{ item }}'
  become: true
  delay: 10
  register: result
  retries: 20
  until: result is not failed
  when:
    - ansible_os_family == 'Debian'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
