# This is a helper playbook to be included in gnome_settings.yml
# It uses the dconf ansible plugin to set dconf/gnome settings.
# This helper function only works under Linux:
# - You can't have it use the DBUS_SESSION_BUS_ADDRESS variable (x for OpenBSD)
# - It will write a dconf setting even if gnome isn't aware of its presence
# - It's idempotent
---
- name: 'dconf_module : set {{ item.key }} dconf setting to "{{ item.value }}"'
  dconf:
    key: '{{ item.path }}/{{ item.key }}'
    value: '"{{ item.value }}"'
  tags: 'gnome_settings'
  when:
    - ansible_system == 'Linux'
    - 'ansible_os_family in item.os_family|default([ansible_os_family])'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
    - 'inventory_hostname in item.include_hosts|default([inventory_hostname])'
