---
- name: '_custom_add_packages: add {{ item.package }} to package install list'
  set_fact:
    packages_to_install: '{{ packages_to_install | default([]) | union([item.package]) }}'
  changed_when: true
  notify: '{{ ["update package cache", "print packages_to_install", "install packages", "set up virtualization",
    "add user to groups for virtualization"] | union(custom_handlers | default([])) }}'
  tags: 'packages'
  when:
    - 'ansible_os_family in item.os_family|default([ansible_os_family])'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
    - 'inventory_hostname in item.include_hosts|default([inventory_hostname])'
