# This is a helper tasks file which:
#   - Creates any directories needed for the files
#   - Copies a list of files either from the ansible server or the web
#   - Adds custome lines to the files
---
- name: '_custom_files : ensure {{ item.dest | dirname | expanduser }} exists'
  file:
    path: '{{ item.dest | dirname | expanduser }}'
    owner: '{{ item.owner | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '{{ item.dirmode | default(omit) }}'
    state: 'directory'
  become: '{{ item.become | default(omit) }}'
  tags:
    - 'configs'
    - 'customfiles'
    - 'serverconfigs'
    - 'userconfigs'
  when:
    - 'ansible_os_family in item.os_family|default([ansible_os_family])'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
    - 'inventory_hostname in item.include_hosts|default([inventory_hostname])'

- name: '_custom_files : copy {{ item.src }}'
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.owner | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
  become: '{{ item.become | default(omit) }}'
  notify: '{{ custom_handlers | default([]) }}'
  tags:
    - 'configs'
    - 'customfiles'
    - 'serverconfigs'
    - 'userconfigs'
  when:
    - item.type == 'file'
    - 'ansible_os_family in item.os_family|default([ansible_os_family])'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
    - 'inventory_hostname in item.include_hosts|default([inventory_hostname])'

- block:
    - name: '_custom_files : download {{ item.src }}'
      get_url:
        url: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: '{{ item.owner | default(omit) }}'
        group: '{{ item.group | default(omit) }}'
        mode: '{{ item.mode | default(omit) }}'
      become: '{{ item.become | default(omit) }}'
      notify: '{{ custom_handlers | default([]) }}'
      when: item.type == "web"
  rescue:
    - name: '_custom_files : log download custom files from web sources failed'
      set_fact:
        task_failures: '{{ task_failures | default([]) | union(["download custom files " + item.src ]) }}'
      changed_when: true
      notify: list failed tasks
  tags:
    - 'configs'
    - 'customfiles'
    - 'serverconfigs'
    - 'userconfigs'
  when:
    - 'ansible_os_family in item.os_family|default([ansible_os_family])'
    - 'inventory_hostname not in item.exclude_hosts|default([])'
    - 'inventory_hostname in item.include_hosts|default([inventory_hostname])'
