# sshserver defaults
#
## Changes should not be made to this file. They should be made in vars/main.yml.
#
---
## Custom configuration options
## *_custom_files is a list of files that can be installed from the ansible server or a web site
# - type: can be 'file' or 'web'
# - src: path to file on ansible server or a URL
# - dest: the destination on the target system
# - mode: permissions on the destination file
# - owner/group: ownership of the destination file
# - dirmode: the permissions on any directories created in the destination file path
# - become: if elevated access is required to write the file
# - os_family: a list of ansible_os_family values for which the file pertains
# - exclude_hosts: a list of inventory_hostname values for which this item should be skipped
#
# desktop_custom_files:
#   - {type: 'web', src: 'https://yoursite.com/yourfile.txt', dest: '~/.yourfile', os_family: ['OpenBSD']}
sshserver_custom_files: []

## *_custom_includes is a list of files that can be installed from the ansible server or a web site
# - path: path to file on the target system to modify
# - line: line to add/change
# - regexp: regular expression to use when looking for a line to change
# - backrefs: whether to enable use of backreferences in line to matches in regexp (e.g. '\1 new text \2')
# - insertafter: a line to insert 'line' after if regexp does not match (default: EOF)
# - insertbefore: a line to insert 'line' before if regexp does not match and insertafter is not set (e.g. BOF)
# - mode: permissions on the destination file
# - owner/group: ownership of the destination file
# - create: should the file be created if it does not exist (default: false)
# - backup: whether to make a backup of the unchanged file (default: false)
# - become: if elevated access is required to write the file
# - os_family: a list of ansible_os_family values for which the include pertains
# - exclude_hosts: a list of inventory_hostname values for which this item should be skipped
#
# desktop_custom_includes:
#   - {path: '~/.profile', line: '[ -r ~/.profile.local ] && . ~/.profile.local'}
sshserver_custom_includes: []

## *_custom_settings is a list settings to add either to foo.conf or foo.conf.d/some-file.conf
# - dest_d: a destination file to be created/overwritten with a configuration option (e.g. /etc/foo.conf.d/1-foo.conf)
# - dest_f: a configuration file to modify with a configuration option
# - line: configuration line to change/add
# - regexp: regular expression to use when looking for a line to change
# - backrefs: whether to enable use of backreferences in line to matches in regexp (e.g. '\1 new text \2')
# - insertafter: a line to insert 'line' after if regexp does not match (default: EOF)
# - insertbefore: a line to insert 'line' before if regexp does not match and insertafter is not set (e.g. BOF)
# - mode: permissions on the destination file
# - owner/group: ownership of the destination file
# - dirmode: the permissions on any directories created in the destination file path
# - backup: whether to make a backup of the unchanged file (default: false)
# - become: if elevated access is required to write the file
# - os_family: a list of ansible_os_family values for which the setting pertains
# - exclude_hosts: a list of inventory_hostname values for which this item should be skipped
#
# desktop_custom_settings:
#   - {dest_d: '/etc/ssh/sshd_config.d/10-permit-root.conf', line: 'PermitRootLogin prohibit-password'}
sshserver_custom_settings: []

## IF SSH KEYS ARE DEFINED IN vars/main.yml, ENCRYPT IT USING ansible-vault

## Define keys for multiple servers: they will be put in ~/.ssh
# ssh_host_keys:
#   name: host1
#     - file: ed25519
#       private_key: |
#         -----BEGIN OPENSSH PRIVATE KEY-----
#         really private key stuff goes here!
#         -----END OPENSSH PRIVATE KEY-----
#       public_key: |
#         ssh-ed25519 AAAAC3NzaCpubkeystuff root@host1
#     - file: id_rsa
#       private_key: |
#         -----BEGIN OPENSSH PRIVATE KEY-----
#         other private key stuff goes here!!
#         -----END OPENSSH PRIVATE KEY-----
#       public_key: |
#         ssh-rsa AAAAB3NzaC1yc2pubkeystuff root@host1
#   name: host2
#     - file: ed25519
#       private_key: |
#         -----BEGIN OPENSSH PRIVATE KEY-----
#         really private key stuff goes here!
#         -----END OPENSSH PRIVATE KEY-----
#       public_key: |
#         ssh-ed25519 AAAAC3NzaCpubkeystuff root@host2
#     - file: id_rsa
#       private_key: |
#         -----BEGIN OPENSSH PRIVATE KEY-----
#         other private key stuff goes here!!
#         -----END OPENSSH PRIVATE KEY-----
#       public_key: |
#         ssh-rsa AAAAB3NzaC1yc2pubkeystuff root@host2
